<<<<<<< Updated upstream
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
=======
import { Col, Image, Row } from "react-bootstrap";
import Master from "../components/Master";
import Link from "next/link";

function Index() {
	return (
		<Master>
			<Image
				src="/assets/images/HeaderWebNew.png"
				alt="Header Web"
				className="header-web"
			/>
			<Row className="justify-content-center bg-landing h-100">
				<Col lg={6} className="position-relative" style={{ zIndex: 1 }}>
					<h1 className="mt-3 text-center font-quick-sand-bold font-size-30">
						Mainkan quiz Pristime
						<br />
						It's Pristine8.6+ Time versi Kamu!
					</h1>
					<Row className="justify-content-center">
						<Col lg={4}>
							<Image
								src="/assets/images/Pristime_logo.png"
								alt="Pristime Logo"
								fluid
							/>
						</Col>
					</Row>
					<Row className="justify-content-center mb-2">
						<Col lg={6}>
							<Image
								src="/assets/images/Cover.png"
								alt="Cover"
								fluid
							/>
						</Col>
					</Row>
					<Row className="justify-content-center mb-4">
						<Col lg={10}>
							<div className="color-green text-center font-size-20">
								Dapatkan <strong>FREE STARTER KIT</strong>
								<br />
								di event Pristime, Ciwalk Bandung
							</div>
						</Col>
					</Row>
					<Row className="justify-content-center">
						<Col lg={5} className="d-grid">
							<Link href="/question-one">
								<a className="rounded-pill bg-light-green border-white text-center font-quick-sand-bold font-size-18 py-1">
									MAIN SEKARANG!
								</a>
							</Link>
						</Col>
					</Row>
				</Col>
			</Row>
		</Master>
	);
}
>>>>>>> Stashed changes

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
